import type { Metadata } from "next";
import { Geist, Lexend } from "next/font/google";
import "./globals.css";
import AuthQueryProvider from "@/providers/QueryProvider";
import { ToastContainer } from "react-toastify";
import AuthProvider from "@/context/authContext";
import SessionContextProvider from "@/context/sessionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Lexend({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <AuthQueryProvider>
          <ToastContainer />
          <AuthProvider>
            <SessionContextProvider>{children}</SessionContextProvider>
          </AuthProvider>
        </AuthQueryProvider>
      </body>
    </html>
  );
}
